# Generated by Django 3.2.6 on 2021-09-04 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210905_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='common',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='news.common'),
            preserve_default=False,
        ),
    ]
