# Generated by Django 3.2.6 on 2022-06-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='common',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='users/'),
        ),
    ]
