# Generated by Django 3.2.6 on 2022-06-07 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_common_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
    ]
