# Generated by Django 3.2.6 on 2022-06-08 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
    ]
