# Generated by Django 3.2.6 on 2022-06-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_favoritespost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=1024),
        ),
    ]
