# Generated by Django 3.2.6 on 2022-06-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritespost',
            name='count_favorite',
            field=models.IntegerField(default=0),
        ),
    ]
