# Generated by Django 3.2.6 on 2022-06-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_favoritespost_count_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritespost',
            name='count_favorite',
        ),
        migrations.AddField(
            model_name='favoritespost',
            name='in_favorite',
            field=models.IntegerField(default=0),
        ),
    ]
