# Generated by Django 3.2.6 on 2022-06-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20220611_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritespost',
            name='in_favorite',
        ),
        migrations.AddField(
            model_name='post',
            name='in_favorite',
            field=models.IntegerField(default=0),
        ),
    ]
