# Generated by Django 3.2.6 on 2022-06-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_post_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
